project:
  type: website

website:
  title: "VatisV(loVe)"
  navbar:
    logo: "images/logo.png"
    left:
      - href: index.qmd
        text: Invitation
      - href: itin.qmd
        text: Itinerary 
      - href: about.qmd
        text: RSVP  

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual

