---
title: "VatisV(loVe)'s Nomadic Tricenary"
---

Dear friends and loved ones,

You're cordially invited to participate in the traveling circus I am planning in celebration of my $30^{th}$ heliocentric circle completion. I have thought long and hard about what would make me happiest and came to the inevitable conclusion that nothing is more precious than seeing as many of your faces as possible.

To facilitate that, I will be embarking on a celebratory *tour de force* around Europe in three stages. I will be taking two weeks off from my current life to make time for contemplating and celebrating what we have already accomplished. I want to have space to enjoy what truly matters — appreciating the great diversity of people with whom I have been and continue to put together the puzzle pieces of my life, in full knowledge of the fact that the anxiety caused by the fear of finding a missing piece at the end is half the fun.

You are welcome to join me for any stretch of time at any of these stages. While this may be the most chaotic birthday celebration invitation you ever receive (I certainly hope so), not only is it supposed to be a metaphor for yours truly, but it is also designed to make it as easy as possible to fit into your schedule. There are three weekends to choose from. Just keep in mind that no matter where and for how long you can come, you are welcome!

So far, the only set event is THE day itself, [***Friday, 14 February***.]{.underline} It's a message. It's meant to be. It's a **party in Brussels**.

We are currently trying to decide on a venue, so it would be most helpful if you could [RSVP to that event here ASAP](about.qmd){.text-secondary}, and no later than [8 December]{.underline}.

Three decades, three stops. So what else is on the menu, you might ask?

<center>[Itinerary](itin.qmd){.btn .btn-lg .btn-primary role="button"}</center>
