---
title: ""
---

# Stage I: Brussels (8-15 February)

Don't believe in celebrating off-date? Want to come get a tattoo with me? Interested in sharing a good beer (or consuming other substances)? Want to meet the lovely people who make me miss Belgium daily? Then this stage is for you! The only set event is the fête on THE day, so we will have plenty of opportunities to catch up in the run-up to the celebration.

# Stage II: Budapest (15-18 February)

Want to take a splash in the thermal baths? Curious about my origin story? Want to see what it feels like to live in the EU's pet dictatorship? Love ruin bars? Would you like to enjoy the hospitality of my mother? Then this stage is for you!

# Stage III: Norway (18-23 February)

Miss snow and have a hole in your heart left by the retreat of real winters in Europe? Want to hang out in nature and get a glimpse of Norwegian mountains? Interested in joining the caravan at the stage with greater emphasis on contemplation? Want to try out skiing and/or snowshoeing? Then this stage is for you!

As mentioned, you're invited to come to all three, come to one, come for a day, or drop by for an hour. Bring whomever you would like, let's share the love! Just let me know who is coming so we can make sure everyone is provided for. [Check out the RSVP page](about.qmd){.text-secondary} to indicate your interest in any of the stages, and we can hammer out details together. More information on the itinerary will come shortly (keep your eyes peeled)!

Any questions or clarifications? Just reach out. VatisV(loVe)? Come and find out! Baby, nobody shall get hurt![^1]

[^1]: Terms and Conditions apply :)
